name : first workflow
on :
  push :
    branches:
      - "main"
jobs:
  first-workflow-job:
    name: first job
    runs-on: ubuntu-latest
    steps :
      - name: before
        run: ls
        shell: bash

      - name: run checkout
        uses: actions/checkout@v3
        
      - name: after
        run: ls
        shell: bash


